export enum actionType {
  GET_ALL_ITEMS = "GET_ALL_ITEMS",
  FETCH_ERROR = "FETCH_ERROR",
  DISPLAY_ALERT = "DISPLAY_ALERT",
  HIDE_ALERT = "HIDE_ALERT",
  UPDATE_INPUT = "UPDATE_INPUT",
  REMOVE_ALL = "REMOVE_ALL",
  ADD_ITEM = "ADD_ITEM",
  EDIT_ITEM = "EDIT_ITEM",
  EDITING_ITEM = "EDITING_ITEM",
  TOOGLE_COMPLETE = "TOOGLE_COMPLETE",
  DELETE_ITEM = "DELETE_ITEM",
  IS_LOADING = "IS_LOADING",
}
